// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYhHb_BQuB1xJJz60-yiYl2Lk410a5tBw',
    appId: '1:873689334079:android:1de38d3bcb92e336c9538a',
    messagingSenderId: '873689334079',
    projectId: 'campus-schedule-hub-ec53e',
    storageBucket: 'campus-schedule-hub-ec53e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWmproYrybueiC34GFbhh94lkgCYgVm2M',
    appId: '1:873689334079:web:0a8e7ae0504500f2c9538a',
    messagingSenderId: '873689334079',
    projectId: 'campus-schedule-hub-ec53e',
    authDomain: 'campus-schedule-hub-ec53e.firebaseapp.com',
    storageBucket: 'campus-schedule-hub-ec53e.firebasestorage.app',
    measurementId: 'G-FK8Z43T2QD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkwSG1n8IBugMNq4L6psirDYQ5jC2cR8',
    appId: '1:873689334079:ios:7b952fe8fd86d377c9538a',
    messagingSenderId: '873689334079',
    projectId: 'campus-schedule-hub-ec53e',
    storageBucket: 'campus-schedule-hub-ec53e.firebasestorage.app',
    iosBundleId: 'com.example.campusScheduleHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWmproYrybueiC34GFbhh94lkgCYgVm2M',
    appId: '1:873689334079:web:54120550f56b24c2c9538a',
    messagingSenderId: '873689334079',
    projectId: 'campus-schedule-hub-ec53e',
    authDomain: 'campus-schedule-hub-ec53e.firebaseapp.com',
    storageBucket: 'campus-schedule-hub-ec53e.firebasestorage.app',
    measurementId: 'G-RQ00PKX0S4',
  );

}